// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAx46Qi-RMqit0Il3JQRzk7NeD6s3GMvM',
    appId: '1:433504153958:web:0c97760b8942969604d8a7',
    messagingSenderId: '433504153958',
    projectId: 'mynotes-arkodatta',
    authDomain: 'mynotes-arkodatta.firebaseapp.com',
    storageBucket: 'mynotes-arkodatta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_cD67Bj9c7x03HLzvB_tthUx5PkZP6o',
    appId: '1:433504153958:android:85b348f9cc22335f04d8a7',
    messagingSenderId: '433504153958',
    projectId: 'mynotes-arkodatta',
    storageBucket: 'mynotes-arkodatta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4H5mJQ7UFD7XK4fK0sFJZh72Wb_8SDHU',
    appId: '1:433504153958:ios:67c59b0485f59a2504d8a7',
    messagingSenderId: '433504153958',
    projectId: 'mynotes-arkodatta',
    storageBucket: 'mynotes-arkodatta.appspot.com',
    iosClientId: '433504153958-iqnufvifdgnof2afp50531s9m4raqtqn.apps.googleusercontent.com',
    iosBundleId: 'com.datta.arko.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4H5mJQ7UFD7XK4fK0sFJZh72Wb_8SDHU',
    appId: '1:433504153958:ios:67c59b0485f59a2504d8a7',
    messagingSenderId: '433504153958',
    projectId: 'mynotes-arkodatta',
    storageBucket: 'mynotes-arkodatta.appspot.com',
    iosClientId: '433504153958-iqnufvifdgnof2afp50531s9m4raqtqn.apps.googleusercontent.com',
    iosBundleId: 'com.datta.arko.mynotes',
  );
}
